//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_LEVELS
    {
        public string LEVEL_NO { get; set; }
        public string LEVEL_DSC { get; set; }
        public decimal LEVEL_LEN { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPdate_date { get; set; }
        public string UPdateD_BY { get; set; }
    }
}
