//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_ENTRY
    {
        public Nullable<System.DateTime> Trans_date { get; set; }
        public Nullable<decimal> sale_amt { get; set; }
        public Nullable<decimal> cost_amt { get; set; }
        public Nullable<decimal> margin { get; set; }
        public string status { get; set; }
        public int seq_id { get; set; }
        public string cr_no { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> shift_st_time { get; set; }
        public Nullable<System.DateTime> shift_end_time { get; set; }
        public string till_no { get; set; }
        public string start_trans { get; set; }
        public string end_trans { get; set; }
        public Nullable<decimal> opening_cash { get; set; }
        public Nullable<decimal> End_cash { get; set; }
        public Nullable<decimal> Diff { get; set; }
        public string SHIFT_STATUS { get; set; }
    }
}
