//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVANCE_LOG
    {
        public int Id { get; set; }
        public string Trans_No { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> Amt_Date { get; set; }
    }
}
