//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMENITY_PRODUCT_DETAIL
    {
        public long RES_ID { get; set; }
        public string BARCODE { get; set; }
        public string ROOM_CODE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public string STATUS { get; set; }
        public string TYPE { get; set; }
        public string REMARKS { get; set; }
        public string COMMENTS { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RESERVATION_MAIN RESERVATION_MAIN { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
