//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_INFO
    {
        public long SEQ_NO { get; set; }
        public string CUST_CODE { get; set; }
        public string FUN_TYPE { get; set; }
        public Nullable<System.DateTime> BOOKING_DATE { get; set; }
        public string BOOKING_SLOT { get; set; }
        public string hall_no { get; set; }
        public Nullable<decimal> Guests { get; set; }
        public Nullable<decimal> Per_head { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
