//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_CONFIGURATION
    {
        public int CLIENT_CONFIGURATION_ID { get; set; }
        public bool CAN_SEND_DATA_TO_FBR { get; set; }
        public bool CAN_SEND_EMAIL { get; set; }
        public bool CAN_SEND_SMS { get; set; }
        public bool CAN_SEND_WHATSAPP { get; set; }
    }
}
