//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CUST_CODE { get; set; }
        public string CUST_NAME { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string STATUS { get; set; }
        public string LOCATION { get; set; }
        public System.DateTime DOC { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<decimal> T_POINTS { get; set; }
        public Nullable<int> DISC_CATEGORY_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CUST_ID { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<decimal> T_BALANCE { get; set; }
        public string CITY_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public Nullable<decimal> DISC { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string LOC_ID { get; set; }
    }
}
