//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_DETAIL
    {
        public string CUST_CODE { get; set; }
        public string CDATE { get; set; }
        public string TRANS_NO { get; set; }
        public Nullable<decimal> TRANS_AMT { get; set; }
        public Nullable<decimal> TRANSPOINT { get; set; }
        public Nullable<decimal> REDEMPOINT { get; set; }
        public Nullable<decimal> OPBAL { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
        public string PROMO_CODE { get; set; }
        public Nullable<System.DateTime> PROMO_EXPIRY { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY_CODE { get; set; }
    }
}
