//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILY_ATTENDANCE
    {
        public string EMP_CODE { get; set; }
        public Nullable<decimal> TIME { get; set; }
        public Nullable<System.DateTime> TIME1 { get; set; }
        public Nullable<System.DateTime> TIME2 { get; set; }
        public string BRANCH_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string DESIG_CODE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<decimal> LATE_COMING { get; set; }
        public Nullable<decimal> LATE_SITTING { get; set; }
        public Nullable<decimal> MEMO { get; set; }
        public Nullable<decimal> SHIFT_TIME { get; set; }
        public string SHIFT_ID { get; set; }
    }
}
