//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_MIG_LOG
    {
        public string TAB_NAME { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime GEN_TIME { get; set; }
        public string TYPE { get; set; }
        public string EXCEPTION { get; set; }
    }
}
