//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEAL_DETAIL
    {
        public string barcode { get; set; }
        public string deal_code { get; set; }
        public Nullable<decimal> deal_retail { get; set; }
        public Nullable<decimal> deal_qty { get; set; }
        public int seq { get; set; }
        public string description { get; set; }
        public Nullable<decimal> recipe_retail { get; set; }
    }
}
