//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESIGNATION
    {
        public string DEPT_CODE { get; set; }
        public string DESIG_CODE { get; set; }
        public string DESIG_NAME { get; set; }
        public string DESIG_STRENGTH { get; set; }
        public string DESIG_STATUS { get; set; }
        public string BRANCH_CODE { get; set; }
        public Nullable<decimal> MIN_SALARY { get; set; }
        public Nullable<decimal> MAX_SALARY { get; set; }
        public string CATEGORY_ID { get; set; }
        public Nullable<decimal> STRENGTH { get; set; }
        public Nullable<decimal> ORDER_LEVEL { get; set; }
    }
}
