//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE_FAULT
    {
        public string TICKET_ID { get; set; }
        public string SEQ_ID { get; set; }
        public string FAULT_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual FAULT FAULT { get; set; }
        public virtual TICKET_DETAIL TICKET_DETAIL { get; set; }
    }
}
