//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class DN_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DN_MAIN()
        {
            this.DN_DETAIL = new HashSet<DN_DETAIL>();
        }
    
        public string DN_NO { get; set; }
        public System.DateTime DN_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string DELIVERY_PLACE { get; set; }
        public string TILL_NO { get; set; }
        public string party_code { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string USER_ID { get; set; }
        public string TYPE { get; set; }
        public decimal BY_CASH { get; set; }
        public decimal BY_CARD { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public string CARD_NO { get; set; }
        public string CANCEL { get; set; }
        public string VOID_UID { get; set; }
        public string DISC_UID { get; set; }
        public string CANCEL_UID { get; set; }
        public string PRC_CH_UID { get; set; }
        public string EXCHNG_UID { get; set; }
        public string REFUND_UID { get; set; }
        public Nullable<decimal> DISC_RATE { get; set; }
        public Nullable<decimal> DISC_AMNT { get; set; }
        public Nullable<decimal> TILL_DISC { get; set; }
        public string STATUS { get; set; }
        public string REFERENCE_PERSON { get; set; }
        public string SALESMAN_CDE { get; set; }
        public string SALE_TYPE { get; set; }
        public Nullable<decimal> CASH_AMT { get; set; }
        public Nullable<decimal> CREDIT_AMT { get; set; }
        public Nullable<decimal> BAL_AMT { get; set; }
        public string LOC_ID { get; set; }
        public string CITY_CODE { get; set; }
        public string FLOCK_CODE { get; set; }
        public string BALANCE { get; set; }
        public string PAID_IN { get; set; }
        public string SHIFT { get; set; }
        public Nullable<System.DateTime> SHIFT_START_TIME { get; set; }
        public Nullable<System.DateTime> SHIFT_END_TIME { get; set; }
        public string S_STATUS { get; set; }
        public string PAY_TERMS { get; set; }
        public Nullable<decimal> CUS_DIS { get; set; }
        public Nullable<decimal> FRIEGHT { get; set; }
        public string M_INVOICE { get; set; }
        public string INV_TYPE { get; set; }
        public string SERVICE { get; set; }
        public Nullable<decimal> SERVICE_AMT { get; set; }
        public Nullable<decimal> GST_AMT { get; set; }
        public string BILL_STATUS { get; set; }
        public Nullable<decimal> M_FEE { get; set; }
        public string C_MOB { get; set; }
        public string PROJ_DESC { get; set; }
        public string INST_NOTE { get; set; }
        public string DESCRIPTION { get; set; }
        public string GST_TYPE { get; set; }
        public Nullable<decimal> ADVANCE { get; set; }
        public string C_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string MOB { get; set; }
        public string CUST_ID { get; set; }
        public string CUST_NAME { get; set; }
        public string WAREHOUSE { get; set; }
        public Nullable<System.TimeSpan> TIME_SLOT { get; set; }
        public Nullable<decimal> RET_AMT { get; set; }
        public string TRANSFER_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_DETAIL> DN_DETAIL { get; set; }
        public virtual STAFF_MEMBER STAFF_MEMBER { get; set; }
    }
}
