//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public System.DateTime DOJ { get; set; }
        public decimal SALARY { get; set; }
        public string DEPT_CODE { get; set; }
        public string DESIG_CODE { get; set; }
        public string CATEGORY_ID { get; set; }
        public string EOBI_NO { get; set; }
        public string NIC_NO { get; set; }
        public string SEX { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string RELIGION_CODE { get; set; }
        public string PHONE_NO { get; set; }
        public string ADDRESS { get; set; }
        public string CITY_CODE { get; set; }
        public string STATUS_ID { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string RELATION { get; set; }
        public string CONT_PERSON_ADDRESS { get; set; }
        public string CONT_PERSON_CITY { get; set; }
        public string CONT_PERSON_TEL { get; set; }
        public string BRANCH_CODE { get; set; }
        public string BLOOD { get; set; }
        public byte[] PICTURE { get; set; }
        public string NTN_NO { get; set; }
        public string Rf_code { get; set; }
    }
}
