//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class FBR_POS_ID
    {
        public string POS_ID { get; set; }
        public string NTN { get; set; }
        public string BUSINESS_NAME { get; set; }
        public string BRANCH_NAME { get; set; }
        public string BUSINESS_ADDRESS { get; set; }
        public string CITY { get; set; }
        public string IP_ADDRESS { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string MODE { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string TILL_NO { get; set; }
    }
}
