//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISCALYEAR
    {
        public string FYYEAR { get; set; }
        public System.DateTime STARTDTE { get; set; }
        public System.DateTime ENDDTE { get; set; }
        public string FYSTATUS { get; set; }
        public string CLOSEDBY { get; set; }
        public Nullable<System.DateTime> CLOSEDDTE { get; set; }
        public string V_TYPE { get; set; }
        public string V_NO { get; set; }
        public string VAMT { get; set; }
        public string VACCOUNT_CODE { get; set; }
    }
}
