//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_CHART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GL_CHART()
        {
            this.GL_CHART1 = new HashSet<GL_CHART>();
            this.SUPPLIERs = new HashSet<SUPPLIER>();
        }
    
        public string ACCOUNT_CODE { get; set; }
        public string ACCOUNT_TITLE { get; set; }
        public string MAIN_ACCOUNT { get; set; }
        public string LEVEL_NO { get; set; }
        public string ACCOUNT_CATEGORY { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public Nullable<decimal> OPEN_BAL { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<decimal> OPEN_BAL_CR { get; set; }
        public string CITY_CODE { get; set; }
        public string PARTY_TYPE { get; set; }
        public string PHONE { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string TITLE_URDU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GL_CHART> GL_CHART1 { get; set; }
        public virtual GL_CHART GL_CHART2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER> SUPPLIERs { get; set; }
    }
}
