//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLYEARLYBALANCE
    {
        public string ACCOUNT_CODE { get; set; }
        public Nullable<decimal> OPENDRBAL { get; set; }
        public Nullable<decimal> OPENCRBAL { get; set; }
        public string FYYEAR { get; set; }
    }
}
