//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRFS_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRFS_MAIN()
        {
            this.GRFS_DETAIL = new HashSet<GRFS_DETAIL>();
        }
    
        public string GRF_NO { get; set; }
        public System.DateTime GRF_DATE { get; set; }
        public string STATUS { get; set; }
        public string SUPL_CODE { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string LOCATION { get; set; }
        public string WAREHOUSE { get; set; }
        public string TRANSFER_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRFS_DETAIL> GRFS_DETAIL { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
