//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADVANCE_LOG> ADVANCE_LOG { get; set; }
        public virtual DbSet<AMENITY_PRODUCT_DETAIL> AMENITY_PRODUCT_DETAIL { get; set; }
        public virtual DbSet<AMENITY_PRODUCT_DETAIL_HISTORY> AMENITY_PRODUCT_DETAIL_HISTORY { get; set; }
        public virtual DbSet<AREA> AREAs { get; set; }
        public virtual DbSet<BRANCH> BRANCHes { get; set; }
        public virtual DbSet<BRAND> BRANDs { get; set; }
        public virtual DbSet<CITY> CITies { get; set; }
        public virtual DbSet<CLIENT_CONFIGURATION> CLIENT_CONFIGURATION { get; set; }
        public virtual DbSet<COLOUR> COLOURS { get; set; }
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<CUST_DETAIL> CUST_DETAIL { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMER_DISCOUNT_CATEGORY> CUSTOMER_DISCOUNT_CATEGORY { get; set; }
        public virtual DbSet<DEAL> DEALs { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<DEVICE> DEVICEs { get; set; }
        public virtual DbSet<DEVICE_FAULT> DEVICE_FAULT { get; set; }
        public virtual DbSet<DN_DETAIL> DN_DETAIL { get; set; }
        public virtual DbSet<DN_MAIN> DN_MAIN { get; set; }
        public virtual DbSet<FAULT> FAULTs { get; set; }
        public virtual DbSet<FAVOURITE> FAVOURITEs { get; set; }
        public virtual DbSet<FBR_DATA> FBR_DATA { get; set; }
        public virtual DbSet<FBR_POS_ID> FBR_POS_ID { get; set; }
        public virtual DbSet<GL_CHART> GL_CHART { get; set; }
        public virtual DbSet<GRFS_DETAIL> GRFS_DETAIL { get; set; }
        public virtual DbSet<GRFS_MAIN> GRFS_MAIN { get; set; }
        public virtual DbSet<GRN_DETAIL> GRN_DETAIL { get; set; }
        public virtual DbSet<GRN_MAIN> GRN_MAIN { get; set; }
        public virtual DbSet<GROUP> GROUPS { get; set; }
        public virtual DbSet<JOURNAL> JOURNALs { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<MAIL_INFO> MAIL_INFO { get; set; }
        public virtual DbSet<MANUFACTURAR> MANUFACTURARs { get; set; }
        public virtual DbSet<MEARSURING_UNITS> MEARSURING_UNITS { get; set; }
        public virtual DbSet<NEWS_LETTERS_EMAIL> NEWS_LETTERS_EMAIL { get; set; }
        public virtual DbSet<PARTY_ADDRESS> PARTY_ADDRESS { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<PO_MAIN> PO_MAIN { get; set; }
        public virtual DbSet<PRICE_HISTORY> PRICE_HISTORY { get; set; }
        public virtual DbSet<PRICE_OVERRIDE_LOG> PRICE_OVERRIDE_LOG { get; set; }
        public virtual DbSet<PROD_BALANCE> PROD_BALANCE { get; set; }
        public virtual DbSet<PROD_LOC_REPORT> PROD_LOC_REPORT { get; set; }
        public virtual DbSet<PRODUCT_COLOUR> PRODUCT_COLOUR { get; set; }
        public virtual DbSet<PRODUCT_REVIEW> PRODUCT_REVIEW { get; set; }
        public virtual DbSet<PRODUCT_UAN_LIST> PRODUCT_UAN_LIST { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<RESERVATION_DETAIL> RESERVATION_DETAIL { get; set; }
        public virtual DbSet<RESERVATION_DETAIL_HISTORY> RESERVATION_DETAIL_HISTORY { get; set; }
        public virtual DbSet<RESERVATION_MAIN> RESERVATION_MAIN { get; set; }
        public virtual DbSet<ROOM> ROOMs { get; set; }
        public virtual DbSet<ROOM_CATEGORY> ROOM_CATEGORY { get; set; }
        public virtual DbSet<ROOM_TYPE> ROOM_TYPE { get; set; }
        public virtual DbSet<SEC_FUNCTIONS> SEC_FUNCTIONS { get; set; }
        public virtual DbSet<SEC_USER_FUNCTIONS> SEC_USER_FUNCTIONS { get; set; }
        public virtual DbSet<SMS_REG> SMS_REG { get; set; }
        public virtual DbSet<STAFF_MEMBER> STAFF_MEMBER { get; set; }
        public virtual DbSet<STAFF_STATUS> STAFF_STATUS { get; set; }
        public virtual DbSet<STATE> STATEs { get; set; }
        public virtual DbSet<STOCK_DETAIL> STOCK_DETAIL { get; set; }
        public virtual DbSet<STOCK_MAIN> STOCK_MAIN { get; set; }
        public virtual DbSet<SUB_GROUPS> SUB_GROUPS { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERs { get; set; }
        public virtual DbSet<SUPPLIER_PRODUCTS> SUPPLIER_PRODUCTS { get; set; }
        public virtual DbSet<TICKET_DETAIL> TICKET_DETAIL { get; set; }
        public virtual DbSet<TICKET_MAIN> TICKET_MAIN { get; set; }
        public virtual DbSet<TILL_USERS> TILL_USERS { get; set; }
        public virtual DbSet<TotalCountHit> TotalCountHits { get; set; }
        public virtual DbSet<TRANS_DT> TRANS_DT { get; set; }
        public virtual DbSet<TRANS_MN> TRANS_MN { get; set; }
        public virtual DbSet<TRANSFER_DETAIL> TRANSFER_DETAIL { get; set; }
        public virtual DbSet<TRANSFER_MAIN> TRANSFER_MAIN { get; set; }
        public virtual DbSet<USER_PERMISSION> USER_PERMISSION { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WAREHOUSE> WAREHOUSEs { get; set; }
        public virtual DbSet<WAST_DETAIL> WAST_DETAIL { get; set; }
        public virtual DbSet<WAST_MAIN> WAST_MAIN { get; set; }
        public virtual DbSet<ACCOUNT_ENTRY> ACCOUNT_ENTRies { get; set; }
        public virtual DbSet<ACCOUNT_LEVELS> ACCOUNT_LEVELS { get; set; }
        public virtual DbSet<BOOKING_INFO> BOOKING_INFO { get; set; }
        public virtual DbSet<DAILY_ATTENDANCE> DAILY_ATTENDANCE { get; set; }
        public virtual DbSet<DATA_MIG_LOG> DATA_MIG_LOG { get; set; }
        public virtual DbSet<DAYS_OF_WEEK> DAYS_OF_WEEK { get; set; }
        public virtual DbSet<DEAL_DETAIL> DEAL_DETAIL { get; set; }
        public virtual DbSet<DESIGNATION> DESIGNATIONs { get; set; }
        public virtual DbSet<DIST_AREA> DIST_AREA { get; set; }
        public virtual DbSet<EMP_CATEGORY> EMP_CATEGORY { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEES { get; set; }
        public virtual DbSet<FISCALYEAR> FISCALYEARs { get; set; }
        public virtual DbSet<GL_CATEGORIES> GL_CATEGORIES { get; set; }
        public virtual DbSet<GLYEARLYBALANCE> GLYEARLYBALANCEs { get; set; }
        public virtual DbSet<GZTTD_HOLIDAY> GZTTD_HOLIDAY { get; set; }
        public virtual DbSet<INV_STOCK_TAKE_ENTRY> INV_STOCK_TAKE_ENTRY { get; set; }
        public virtual DbSet<ITEM_MOVEMENT> ITEM_MOVEMENT { get; set; }
        public virtual DbSet<LEAVE_REASONS> LEAVE_REASONS { get; set; }
        public virtual DbSet<LEAVES_BALANCES> LEAVES_BALANCES { get; set; }
        public virtual DbSet<LEAVES_HISTORY> LEAVES_HISTORY { get; set; }
        public virtual DbSet<MIGRATION_LOG> MIGRATION_LOG { get; set; }
        public virtual DbSet<OVERTIME> OVERTIMEs { get; set; }
        public virtual DbSet<PO_DETAIL> PO_DETAIL { get; set; }
        public virtual DbSet<PROD_SIZE> PROD_SIZE { get; set; }
        public virtual DbSet<PROMO_INFO> PROMO_INFO { get; set; }
        public virtual DbSet<QUALIFICATION_DETAIL> QUALIFICATION_DETAIL { get; set; }
        public virtual DbSet<QUALIFICATION_MAIN> QUALIFICATION_MAIN { get; set; }
        public virtual DbSet<RELIGION> RELIGIONs { get; set; }
        public virtual DbSet<SALE_TRANS> SALE_TRANS { get; set; }
        public virtual DbSet<SALESMAN> SALESMen { get; set; }
        public virtual DbSet<SHIFTS_MAIN> SHIFTS_MAIN { get; set; }
        public virtual DbSet<SHIFTS_ROASTER> SHIFTS_ROASTER { get; set; }
        public virtual DbSet<TIMESWIPE> TIMESWIPES { get; set; }
        public virtual DbSet<V_DETAIL> V_DETAIL { get; set; }
        public virtual DbSet<V_MAIN> V_MAIN { get; set; }
        public virtual DbSet<V_TYPES> V_TYPES { get; set; }
        public virtual DbSet<WORK_EXPERIENCE> WORK_EXPERIENCE { get; set; }
    }
}
