//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNAL
    {
        public string DOC_SEQ { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<System.DateTime> TRANS_DTE { get; set; }
        public string REFERENCE { get; set; }
        public string REFERENCE_PERSON { get; set; }
        public Nullable<System.DateTime> REFERENCE_DTE { get; set; }
        public string NARRATION { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string PARTY_TYPE { get; set; }
        public string PARTY_CODE { get; set; }
        public string STATUS { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> INSERTED_DTE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DTE { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public string V_TYPE { get; set; }
        public string CHQ_NBR { get; set; }
        public string BANK_CODE { get; set; }
        public string PAY_TYPE { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string ACCOUNT_TITTLE { get; set; }
        public string ACCOUNT_CODE_IE { get; set; }
        public string ACCOUNT_TITTLE_IE { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string BANK_NAME { get; set; }
        public string PAYMENT_PURPOSE { get; set; }
        public string COMPANY { get; set; }
        public string AMOUNT_IN_WORDS { get; set; }
        public Nullable<long> RES_ID { get; set; }
        public string ROOM_CODE { get; set; }
        public Nullable<decimal> CREDIT_AMOUNT { get; set; }
        public Nullable<decimal> DEBIT_AMOUNT { get; set; }
        public string STAFF_CODE { get; set; }
        public string BOOK_NO { get; set; }
        public string BILL_NO { get; set; }
    
        public virtual STAFF_MEMBER STAFF_MEMBER { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
