//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVES_HISTORY
    {
        public string EMP_CODE { get; set; }
        public System.DateTime LEAVE_FROM { get; set; }
        public System.DateTime LEAVE_TO { get; set; }
        public string LEAVE_TYPE { get; set; }
        public string REASON_CODE { get; set; }
        public string APPROVED_BY { get; set; }
        public string AUTHORIZED_BY { get; set; }
        public string REMARKS { get; set; }
        public string DAYS { get; set; }
        public Nullable<System.DateTime> TIME_STAMP { get; set; }
    }
}
