//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVES_BALANCES
    {
        public string EMP_CODE { get; set; }
        public Nullable<decimal> SICK { get; set; }
        public Nullable<decimal> CASUAL { get; set; }
        public Nullable<decimal> VACATION { get; set; }
        public Nullable<decimal> CPL { get; set; }
        public Nullable<decimal> LEAVE_FLAG { get; set; }
    }
}
