//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANUFACTURAR
    {
        public string Man_CODE { get; set; }
        public string Man_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT_PERSON { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string STATUS { get; set; }
        public string LOCATION { get; set; }
        public string STN_NO { get; set; }
        public string NTN_NO { get; set; }
        public string GST_TYPE { get; set; }
        public string PAY_TERMS { get; set; }
        public Nullable<decimal> PAY_DAYS { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string party_type { get; set; }
        public Nullable<int> DISC_CATEGORY_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string man_BAR_CODE { get; set; }
        public string account_code { get; set; }
        public string Cust_type { get; set; }
        public string lead_days { get; set; }
        public string FUNC_WITH { get; set; }
        public string FUN_TYPE { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BOOKING_DATE { get; set; }
        public string BOOKING_SLOT { get; set; }
        public string hall_no { get; set; }
        public Nullable<decimal> Guests { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Per_head { get; set; }
        public string CITY_CODE { get; set; }
        public string Area_code { get; set; }
        public string Discount { get; set; }
    }
}
