//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIGRATION_LOG
    {
        public int log_id { get; set; }
        public string table_name { get; set; }
        public Nullable<int> table_rowcount { get; set; }
        public string table_min_val { get; set; }
        public string table_max_val { get; set; }
        public string inserted_by { get; set; }
        public Nullable<System.DateTime> insertion_date { get; set; }
    }
}
