//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_LETTERS_EMAIL
    {
        public long ID { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
    }
}
