//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVERTIME
    {
        public string EMP_CODE { get; set; }
        public System.DateTime OT_DATE { get; set; }
        public Nullable<decimal> OT_HOURS { get; set; }
        public string REMARKS { get; set; }
    }
}
