//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_DETAIL
    {
        public string PO_NO { get; set; }
        public string BARCODE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public decimal QTY { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public int seq_id { get; set; }
    }
}
