//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICE_HISTORY
    {
        public int SEQ_ID { get; set; }
        public string BARCODE { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public Nullable<decimal> PREV_COST { get; set; }
        public Nullable<decimal> UNIT_RETAIL { get; set; }
        public Nullable<decimal> PREV_RETAIL { get; set; }
        public Nullable<System.DateTime> PRICE_DATE { get; set; }
        public string USER_ID { get; set; }
        public string LOC_ID { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
