//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.AMENITY_PRODUCT_DETAIL = new HashSet<AMENITY_PRODUCT_DETAIL>();
            this.AMENITY_PRODUCT_DETAIL_HISTORY = new HashSet<AMENITY_PRODUCT_DETAIL_HISTORY>();
            this.DN_DETAIL = new HashSet<DN_DETAIL>();
            this.GRFS_DETAIL = new HashSet<GRFS_DETAIL>();
            this.GRN_DETAIL = new HashSet<GRN_DETAIL>();
            this.PRODUCT_REVIEW = new HashSet<PRODUCT_REVIEW>();
            this.PRODUCT_UAN_LIST = new HashSet<PRODUCT_UAN_LIST>();
            this.STOCK_DETAIL = new HashSet<STOCK_DETAIL>();
            this.SUPPLIER_PRODUCTS = new HashSet<SUPPLIER_PRODUCTS>();
            this.TRANS_DT = new HashSet<TRANS_DT>();
            this.TRANSFER_DETAIL = new HashSet<TRANSFER_DETAIL>();
            this.WAST_DETAIL = new HashSet<WAST_DETAIL>();
        }
    
        public string BARCODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SHORT_DESC { get; set; }
        public string DEPT_CODE { get; set; }
        public string GROUP_CODE { get; set; }
        public string SRGOUP_CODE { get; set; }
        public string UAN_NO { get; set; }
        public Nullable<decimal> UNIT_SIZE { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public Nullable<decimal> UNIT_RETAIL { get; set; }
        public Nullable<decimal> P_COST { get; set; }
        public Nullable<decimal> P_RETAIL { get; set; }
        public Nullable<decimal> BULK_RETAIL { get; set; }
        public string GST { get; set; }
        public Nullable<decimal> REORDER_LVL { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string IMPORTED { get; set; }
        public string FLASH_PACK { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string LOCATION { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public Nullable<System.DateTime> PROM_START_DTE { get; set; }
        public Nullable<System.DateTime> PROM_END_DTE { get; set; }
        public string PROMOTION { get; set; }
        public Nullable<decimal> PACK_RATE { get; set; }
        public Nullable<decimal> PACK_QTY { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> OLD_RETAIL { get; set; }
        public string MODEL { get; set; }
        public Nullable<decimal> LOWEST_RETAIL { get; set; }
        public string EXEMPT { get; set; }
        public string COLOURS { get; set; }
        public Nullable<decimal> M_COST { get; set; }
        public Nullable<decimal> STOCKS { get; set; }
        public Nullable<decimal> MIN_QTY { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public string TYPE { get; set; }
        public string URDU { get; set; }
        public string SIZE_NAME { get; set; }
        public string SALES_MAN_CODE { get; set; }
        public Nullable<decimal> MINI_RATE { get; set; }
        public Nullable<decimal> F_MARGIN { get; set; }
        public string SCALE_ITEM { get; set; }
        public Nullable<decimal> GST_PER { get; set; }
        public Nullable<decimal> MIN_RETAIL { get; set; }
        public Nullable<decimal> MARKET_RETAIL { get; set; }
        public Nullable<decimal> CTN_PCS { get; set; }
        public Nullable<decimal> FREE_QTY { get; set; }
        public string COMMENTS { get; set; }
        public string REFERENCE_CODE { get; set; }
        public string IMG_DESC { get; set; }
        public string IMG_DESC2 { get; set; }
        public string SEARCHING_WORDS { get; set; }
        public string BRAND_ID { get; set; }
        public Nullable<decimal> PROMO_PER { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMENITY_PRODUCT_DETAIL> AMENITY_PRODUCT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMENITY_PRODUCT_DETAIL_HISTORY> AMENITY_PRODUCT_DETAIL_HISTORY { get; set; }
        public virtual BRAND BRAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DN_DETAIL> DN_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRFS_DETAIL> GRFS_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRN_DETAIL> GRN_DETAIL { get; set; }
        public virtual PROD_BALANCE PROD_BALANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_REVIEW> PRODUCT_REVIEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_UAN_LIST> PRODUCT_UAN_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STOCK_DETAIL> STOCK_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_PRODUCTS> SUPPLIER_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANS_DT> TRANS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFER_DETAIL> TRANSFER_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAST_DETAIL> WAST_DETAIL { get; set; }
    }
}
