//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_LOC_REPORT
    {
        public string BARCODE { get; set; }
        public string BRANCH_ID { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<decimal> SALE_QTY { get; set; }
        public Nullable<decimal> SALE_AMOUNT { get; set; }
        public Nullable<decimal> CURRENT_QTY { get; set; }
        public string CURRENT_LOC { get; set; }
        public Nullable<decimal> TRANSFER_IN_QTY { get; set; }
        public Nullable<decimal> TRANSFER_IN_AMOUNT { get; set; }
        public Nullable<decimal> TRANSFER_OUT_QTY { get; set; }
        public Nullable<decimal> TRANSFER_OUT_AMOUNT { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<decimal> WAST_QTY { get; set; }
        public Nullable<decimal> WAST_AMOUNT { get; set; }
        public Nullable<decimal> GAIN_QTY { get; set; }
        public Nullable<decimal> GAIN_AMOUNT { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
    }
}
