//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_REVIEW
    {
        public string BARCODE { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string REVIEWS { get; set; }
        public string RATING { get; set; }
        public string STATUS { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
