//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMO_INFO
    {
        public string EMAIL { get; set; }
        public string CODE { get; set; }
        public bool IS_CONSUMED { get; set; }
        public string TRANS_NO { get; set; }
        public Nullable<System.DateTime> TRANS_DATE { get; set; }
        public int ID { get; set; }
        public string MOBILE { get; set; }
        public string NAME { get; set; }
    }
}
