//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUALIFICATION_DETAIL
    {
        public string QUALI_CODE { get; set; }
        public string QUALI_SUB_CODE { get; set; }
        public string QUALI_DETAIL { get; set; }
    }
}
