//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION_DETAIL
    {
        public long RES_ID { get; set; }
        public string ROOM_CODE { get; set; }
        public string TABLES_CODE { get; set; }
        public System.DateTime CHECKIN_DATETIME { get; set; }
        public Nullable<System.DateTime> ESTIMATED_CHECKOUT_DATETIME { get; set; }
        public System.DateTime CHECKOUT_DATETIME { get; set; }
        public string RES_STS { get; set; }
        public Nullable<decimal> RATE_PER_DAY { get; set; }
        public Nullable<decimal> OTHER_CHARGES { get; set; }
        public Nullable<decimal> SERVICES_CHARGES { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public Nullable<int> ADULTS { get; set; }
        public Nullable<int> CHILDREN { get; set; }
        public Nullable<int> REVS_DAYS { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string STATUS { get; set; }
    
        public virtual RESERVATION_MAIN RESERVATION_MAIN { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
