//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVATION_MAIN()
        {
            this.AMENITY_PRODUCT_DETAIL = new HashSet<AMENITY_PRODUCT_DETAIL>();
            this.AMENITY_PRODUCT_DETAIL_HISTORY = new HashSet<AMENITY_PRODUCT_DETAIL_HISTORY>();
            this.RESERVATION_DETAIL = new HashSet<RESERVATION_DETAIL>();
            this.RESERVATION_DETAIL_HISTORY = new HashSet<RESERVATION_DETAIL_HISTORY>();
        }
    
        public long RES_ID { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public string SUPL_CODE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string CITY { get; set; }
        public string ADDRESS { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string E_MAIL { get; set; }
        public string ID_TYPE { get; set; }
        public string ID_NO { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> TOTAL_AMT { get; set; }
        public Nullable<decimal> AMOUNT_PAID { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string COMPANY { get; set; }
        public string STATUS { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMENITY_PRODUCT_DETAIL> AMENITY_PRODUCT_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMENITY_PRODUCT_DETAIL_HISTORY> AMENITY_PRODUCT_DETAIL_HISTORY { get; set; }
        public virtual CITY CITY1 { get; set; }
        public virtual COUNTRY COUNTRY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION_DETAIL> RESERVATION_DETAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVATION_DETAIL_HISTORY> RESERVATION_DETAIL_HISTORY { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
