//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE_TRANS
    {
        public string BARCODE { get; set; }
        public string deal_code { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> retail { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string trans_no { get; set; }
        public string seq_nbr { get; set; }
    }
}
