//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_FUNCTIONS
    {
        public string FUNCTION_ID { get; set; }
        public string CODE { get; set; }
        public string DSC { get; set; }
    }
}
