//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFTS_MAIN
    {
        public string SHIFT_ID { get; set; }
        public string SHIFT_NAME { get; set; }
        public Nullable<System.DateTime> SHIFT_FROM { get; set; }
        public Nullable<System.DateTime> SHIFT_TO { get; set; }
    }
}
