//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFTS_ROASTER
    {
        public string EMP_CODE { get; set; }
        public string SHIFT_ID { get; set; }
        public System.DateTime SHIFT_DATE { get; set; }
        public string DAY_OFF { get; set; }
    }
}
