//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_REG
    {
        public decimal ID { get; set; }
        public string phone_num { get; set; }
        public string sms_msg { get; set; }
        public Nullable<System.DateTime> sent_time { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    }
}
