//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_DETAIL
    {
        public string STOCK_NO { get; set; }
        public string BARCODE { get; set; }
        public decimal COST { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> FREE_QTY { get; set; }
        public decimal GST_AMOUNT { get; set; }
        public string DOC_TYPE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string BARCH_NO { get; set; }
        public Nullable<decimal> INVOICE_AMOUNT { get; set; }
        public Nullable<decimal> OLD_COST { get; set; }
        public string S_NO { get; set; }
        public string FARM_CODE { get; set; }
        public string FLOCK_CODE { get; set; }
        public Nullable<decimal> M_COST { get; set; }
        public string GST_FLAG { get; set; }
        public string DIS_FLAG { get; set; }
        public Nullable<decimal> NON_GST_CODE { get; set; }
        public Nullable<decimal> DIS_PERCENT { get; set; }
        public Nullable<decimal> GST_PERCENT { get; set; }
        public Nullable<decimal> ONHAND { get; set; }
        public Nullable<decimal> DIS_AMT { get; set; }
        public Nullable<decimal> GST_AMT { get; set; }
        public Nullable<decimal> FREIGHT { get; set; }
        public Nullable<decimal> CODE_QTY { get; set; }
        public Nullable<decimal> TRANSFER_QTY { get; set; }
        public string LOC_ID { get; set; }
        public Nullable<decimal> ACT_COST { get; set; }
        public Nullable<int> COLOUR { get; set; }
        public string WAREHOUSE { get; set; }
        public string TRANSFER_STATUS { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual STOCK_MAIN STOCK_MAIN { get; set; }
    }
}
