//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_GROUPS
    {
        public string SGROUP_CODE { get; set; }
        public string DEPT_CODE { get; set; }
        public string GROUP_CODE { get; set; }
        public string SGROUP_NAME { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string TRANSFER_STATUS { get; set; }
    
        public virtual GROUP GROUP { get; set; }
    }
}
