//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET_DETAIL()
        {
            this.DEVICE_FAULT = new HashSet<DEVICE_FAULT>();
        }
    
        public string TICKET_ID { get; set; }
        public string SEQ_ID { get; set; }
        public string IMEI { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime DIAGNOS_DATE { get; set; }
        public System.DateTime DELIVERY_DATE { get; set; }
        public string BIN_LOCATION { get; set; }
        public string COMMENTS { get; set; }
        public string DEVICE_ID { get; set; }
        public string STATE_ID { get; set; }
        public decimal CHARGES { get; set; }
        public string STAFF_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string COLOUR { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVICE_FAULT> DEVICE_FAULT { get; set; }
        public virtual STAFF_MEMBER STAFF_MEMBER { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual TICKET_MAIN TICKET_MAIN { get; set; }
    }
}
