//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TILL_USERS
    {
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_TYPE { get; set; }
        public string STATUS { get; set; }
        public string USER_PASSWD { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string TRANSFER_STATUS { get; set; }
    }
}
