//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMESWIPE
    {
        public string EMP_CODE { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public string Status { get; set; }
        public string rf_code { get; set; }
        public Nullable<System.TimeSpan> time_log { get; set; }
        public Nullable<System.DateTime> scan_date { get; set; }
        public Nullable<System.TimeSpan> time_out { get; set; }
    }
}
