//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFER_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSFER_MAIN()
        {
            this.TRANSFER_DETAIL = new HashSet<TRANSFER_DETAIL>();
        }
    
        public string DOC_NO { get; set; }
        public System.DateTime DOC_DATE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string DOC_TYPE { get; set; }
        public string LOCATION { get; set; }
        public string REF_NO { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string WAREHOUSE { get; set; }
        public string BRANCH_ID_FROM { get; set; }
        public string BRANCH_ID_TO { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual BRANCH BRANCH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFER_DETAIL> TRANSFER_DETAIL { get; set; }
    }
}
