//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PERMISSION
    {
        public long USER_PERMISSION_ID { get; set; }
        public string USER_ID { get; set; }
        public int PERMISSION_ID { get; set; }
    
        public virtual PERMISSION PERMISSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
