//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.USER_PERMISSION = new HashSet<USER_PERMISSION>();
        }
    
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_TYPE { get; set; }
        public string STATUS { get; set; }
        public string USER_PASSWD { get; set; }
        public System.DateTime DOC { get; set; }
        public string INSERTED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string TRANSFER_STATUS { get; set; }
        public string EMAIL { get; set; }
        public string LOC_ID { get; set; }
        public Nullable<bool> NEWS_LETTER { get; set; }
        public string MOBILE { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PERMISSION> USER_PERMISSION { get; set; }
    }
}
