//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DETAIL
    {
        public string V_TYPE { get; set; }
        public string V_NO { get; set; }
        public decimal V_SNO { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string V_NARRATION { get; set; }
        public Nullable<decimal> DR_AMOUNT { get; set; }
        public Nullable<decimal> CR_AMOUNT { get; set; }
    }
}
