//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MAIN
    {
        public string V_TYPE { get; set; }
        public string V_NO { get; set; }
        public System.DateTime V_DATE { get; set; }
        public decimal V_AMOUNT { get; set; }
        public string V_REMARKS { get; set; }
        public string REF_DOCUMENT { get; set; }
        public Nullable<System.DateTime> REF_DOC_DATE { get; set; }
        public string REF_DOC_PERSON { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public string INSERTED_BY { get; set; }
        public string POSTED_BY { get; set; }
        public Nullable<System.DateTime> POSTED_DATE { get; set; }
        public string chq_nbr { get; set; }
    }
}
