//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string LOC_ID { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
    }
}
