//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_EXPERIENCE
    {
        public string EMP_CODE { get; set; }
        public string EMPLOYER_NAME { get; set; }
        public string EMPLOYER_ADDRESS { get; set; }
        public string EMPLOYER_CITY { get; set; }
        public System.DateTime JOB_FROM { get; set; }
        public System.DateTime JOB_TO { get; set; }
        public Nullable<decimal> SALARY { get; set; }
    }
}
